### ISSUE TITLE
process data

### ISSUE THREAD

**Issue by yihaoyao402** [keonlee9420/DiffGAN-TTS#17]
hi, when i use VCTK dataset, process has a problem called "UnboundLocalError: local variable 'f0' referenced before assignment"
but using LJSpeech is ok. By the way ,when i train the naive model by LJSpeech, it comes to a problem called " GaussiDiffusion has no attribute cond in torch", is this caused by torch version?

**Comment by quiteconfused** [comment]
i too get the VCTK preprocess error when i follow the instructions .... going to try right now with LJSpeech

`
2023-03-01 18:58:07.058104: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21092 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:0b:00.0, compute capability: 8.6
Processing Data ...
  0%|▏                                                                                                   | 1/462 [00:00<00:01, 305.46it/s]  0%|                                                                                                             | 0/109 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/XXXXXXXXXXX/DiffGAN-TTS/./preprocess.py", line 19, in <module>
    preprocessor.build_from_path()
  File "/home/XXXXXXXXXXX/DiffGAN-TTS/preprocessor/preprocessor.py", line 133, in build_from_path
    if len(f0) > 0:
UnboundLocalError: local variable 'f0' referenced before assignment
`

**Comment by yihaoyao402** [comment]
hi, sorry to bother you, did you find the way to solve this problem? @quiteconfused

**Comment by isjwdu** [comment]
same error
